from flask import Blueprint, request, jsonify
from jemai_rag import jemai_retrieve
from jemai_composer import is_compose_request, compose_song

jemai_chat_bp = Blueprint("jemai_chat", __name__)

_SUGGESTIONS = ["Explain this lesson", "Give me a hint", "Write me a song"]

_NO_MATCH = (
    "I could not find a direct match in the JAM lesson files yet. "
    "Try asking about loop, beat, note, wave, envelope, or sound — "
    "or ask me to write you a song!"
)


def _build_answer(top):
    """
    Build a helpful answer from RAG results.
    Handles different content types and generates useful responses.
    """
    snippet = (top.get("snippet") or "").strip()
    title = top.get("doc_title") or top.get("title", "")
    section = top.get("section", "")
    section_type = top.get("section_type", "")
    goal = top.get("goal", "")
    concepts = top.get("concepts") or []
    source_type = top.get("source_type", "")

    lines = []

    # Start with the title
    if title:
        lines.append(f"**{title}**")

    # For lesson overviews, lead with the goal
    if section_type == "lesson_overview" and goal:
        lines.append(goal)

    # For steps, lead with the step title and content
    if "step" in section_type and section:
        # Extract step number if present
        lines.append(section)

    # For code, format as code block
    if section_type == "lesson_code" and snippet:
        # Format JEM code properly
        lines.append("**Example:**")
        lines.append("```jem")
        lines.append(snippet[:500])
        lines.append("```")
    # For references (DSL_README), show the content directly
    elif source_type == "reference" and snippet:
        lines.append(snippet[:400])
    # For other content, show the snippet
    elif snippet:
        lines.append(snippet[:350])

    # Add concepts summary if available
    if concepts and source_type == "lesson":
        concepts_str = ", ".join(concepts)
        lines.append(f"**Concepts:** {concepts_str}")

    # Add section info for context
    if section and section != title:
        lines.append(f"*From: {section}*")

    return "\n".join(lines) if lines else f"Found in {title}"


@jemai_chat_bp.route("/api/jemai/chat", methods=["POST"])
@jemai_chat_bp.route("/api/jamai/chat", methods=["POST"])  # legacy alias
def jemai_chat():
    data = request.get_json(silent=True) or {}
    message = data.get("message", "").strip()
    lesson_id = data.get("lessonId")
    local_knowledge_context = data.get("localKnowledgeContext", "").strip()
    local_answer = data.get("localAnswer", "").strip()

    if not message:
        return jsonify({"answer": "Please write a question.", "sources": [], "suggestions": []}), 400

    # Song-writing requests get a freshly composed JAM program
    if is_compose_request(message):
        song = compose_song(message)
        answer = "\n".join([
            f"Here is {song['label']} I composed for you:",
            "```jem",
            song["code"].rstrip(),
            "```",
            "Paste it into the Sandbox and press Play! "
            "Ask me for a different mood (happy, sad, spooky, chill, epic, retro) "
            "or tweak the notes yourself.",
        ])
        return jsonify({
            "answer": answer,
            "sources": [{
                "title": "Composing Songs in JAM",
                "id": "COMPOSING_SONGS/intro",
                "file": "COMPOSING_SONGS.md",
                "score": 1.0,
                "source_type": "reference",
            }],
            "suggestions": ["Make it spooky", "Make it chill", "Explain this code"],
        })

    lid = None
    if lesson_id is not None:
        try:
            lid = int(lesson_id)
        except (ValueError, TypeError):
            lid = None

    # Try backend RAG first
    results = jemai_retrieve(message, lesson_id=lid, top_k=3)

    # If we have backend results, use them (highest priority)
    if results:
        answer = _build_answer(results[0])
        sources = [
            {
                "title": r.get("doc_title") or r["title"],
                "id": r["id"],
                "file": r["file"],
                "score": r["score"],
                "source_type": r["source_type"],
            }
            for r in results
        ]
        return jsonify({
            "answer": answer,
            "sources": sources,
            "suggestions": _SUGGESTIONS,
        })

    # No backend results; use local answer generated by frontend if available
    if local_answer:
        answer = local_answer
        # Try to extract source names from local_knowledge_context for attribution
        sources = []
        if local_knowledge_context:
            # Parse sources from context (format: **Title**)
            import re
            titles = re.findall(r'\*\*([^*]+)\*\*', local_knowledge_context)
            sources = [{"title": t, "id": "", "file": "local", "score": 0.8, "source_type": "lesson"} for t in titles[:2]]
        
        return jsonify({
            "answer": answer,
            "sources": sources,
            "suggestions": _SUGGESTIONS,
        })

    # Fallback to formatted local knowledge context if no generated answer
    if local_knowledge_context:
        answer = local_knowledge_context
        return jsonify({
            "answer": answer,
            "sources": [],
            "suggestions": _SUGGESTIONS,
        })

    # No results at all
    return jsonify({"answer": _NO_MATCH, "sources": [], "suggestions": _SUGGESTIONS})